### ISSUE TITLE
team validator

### ISSUE THREAD

**Issue by HeliosVelite** [pkmn/ps#2]
I hope i'm asking this thing in the correct place, if not i'm sorry.

I have a project i'm working on as an hobby and i would like to use the team validation in the sim package, but i'm having some troubles on understanding how it works.
By looking in the test folder I've made a general idea on how to get it to work, but i would like to know if it's possible to adapt it for custom formats and ban lists (and if it is, where should i look to understand how to do this?).

Also, a small off topic: i think that creating a package just for team validation might be pretty useful, as I've asked around and I'm not the only one who is interested in an easy way to import team validation in a project.

Thanks in advance for the patience and great work with these packages!

**Comment by scheibo** [comment]
> By looking in the test folder I've made a general idea on how to get it to work, but i would like to know if it's possible to adapt it for custom formats and ban lists (and if it is, where should i look to understand how to do this?

The `TeamValidator` takes a 	`format: string | Format` in its constructor - you can create a custom `Format` and pass this in when initializing a validator. `Dex.getFormat` provides an example of how to turn `FormatsData` into a `Format`, and `FormatsData` can be found in `sim/config/formats.ts`.

Admittedly, this is not very convenient or intuitive, `@pkmn/sim` is not primarily motivated around exposing a validation API and Pokémon Showdown mostly relies on predefined formats augmented/modified through [Custom Rules](https://github.com/smogon/pokemon-showdown/blob/master/config/CUSTOM-RULES.md)


>  i think that creating a package just for team validation might be pretty useful, as I've asked around and I'm not the only one who is interested in an easy way to import team validation in a project

I agree, though I am not super interested in said package being based on the PS validator because there are innumerable shortcomings and architectural issues with Pokémon Showdown's validator. Something based off of https://github.com/kwsch/PKHeX would make much more sense, as it contains a much more accurate and better architectured validator.

Furthermore, the `TeamValidator` is lumped in with the `@pkmn/sim` package because it actually depends on the `Dex` in `@pkmn/sim` (for `Format`, `RuleTable`, etc) as opposed to the more general `@pkmn/dex-type`-compatible interface in `@pkmn/dex`. If it could be modified to be data-agnostic then it would make more sense to pull out `TeamValidator` into a self contained package, but work would need to be done (preferably upstream) to make `TeamValidator` module-compatible, and I return to the question of whether any work here is worth it given the validator is not of incredibly high quality to begin with.

---

However, I'm happy to add more documentation on how the `TeamValidator` for `@pkmn/sim` could be used/try to make it slightly more ergonomic for standalone use (perhaps a wrapper interface?). Could you elaborate on your use case to help me understand the problem that you're trying to solve?

**Comment by HeliosVelite** [comment]
My use case for this is to validate a team in a certain format, in particular i'm interested in validating a pokemon's moveset, as the mechanics and exceptions you have to keep in mind to do this are quite a lot (you can find a beta of the web app i'm building at heliosteambuilder.herokuapp.com, as you can see the current validation function is quite buggy and inaccurate).

Right now i'm coding a temporary solution to do so by using web sockets and sending a team i need to validate to showdown's server, but i would like to find a solution that is more consistent and less dependent on showdown.

As you mentioned I've also tried to look at PkHeX's code, but unfortunately i don't know C# and so i don't have the slightest idea on how to do that.

**Comment by scheibo** [comment]
If you only care about the formats PS supports (which are baked into `@pkmn/sim`), it should just be:

```ts
import {Team} from '@pkmn/sets';
import {TeamValidator} from '@pkmn/sim';

const validator = new TeamValidator('gen7ou');
console.log(validator.validateTeam(Team.import(`
Alakazam-Mega @ Alakazite
Ability: Magic Guard
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
IVs: 0 Atk
- Psychic
- Focus Blast
- Shadow Ball
- Recover

Tangrowth @ Assault Vest
Ability: Regenerator
EVs: 248 HP / 8 Def / 252 SpD
Sassy Nature
IVs: 30 Atk / 30 Def
- Giga Drain
- Knock Off
- Hidden Power [Ice]
- Earthquake

Gliscor @ Toxic Orb
Ability: Poison Heal
EVs: 244 HP / 152 SpD / 112 Spe
Jolly Nature
- Stealth Rock
- Earthquake
- Toxic
- Roost

Magnezone @ Choice Specs
Ability: Magnet Pull
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
IVs: 0 Atk
- Thunderbolt
- Flash Cannon
- Hidden Power [Fire]
- Volt Switch

Tornadus-Therian @ Rocky Helmet
Ability: Regenerator
EVs: 248 HP / 8 Def / 252 Spe
Timid Nature
- Hurricane
- Heat Wave
- Knock Off
- Defog

Magearna @ Fairium Z
Ability: Soul-Heart
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
IVs: 0 Atk
- Shift Gear
- Calm Mind
- Fleur Cannon
- Focus Blast

`).team));
```

This will output `null` because the team is a valid `'gen7ou'` team. If you change the forum to `gen8ou`, the following will be output:

```
[
  'Alakazam-Mega does not exist in Gen 8.',
  "Alakazam's item Alakazite does not exist in Gen 8.",
  "Tangrowth's move Hidden Power Ice does not exist in Gen 8.",
  'Gliscor does not exist in Gen 8.',
  "Magnezone's move Hidden Power Fire does not exist in Gen 8.",
  'Tornadus-Therian does not exist in Gen 8.',
  'Magearna is in Uber, which is banned.',
  "Magearna's item Fairium Z does not exist in Gen 8."
]
```

You can then either add custom rules as outlined in the documentation I linked earlier (with `@@@`), or you can pass in an entirely `Format` to the `new TeamValidator(...)` call.

**Comment by HeliosVelite** [comment]
I'll try to implement this server-side using custom rules, thanks for the help!
