### ISSUE TITLE
gen7vgc2017 team validation

### ISSUE THREAD

**Issue by HeliosVelite** [pkmn/ps#3]
I've found this weird thing while playing around with the team validator in the sim package.
I pass a team to validate in showdown's export syntax and the format's validation string (in this case `'gen7vgc2017'`) and it returns this error:
`TypeError: Cannot read property 'includeData' of undefined`
`[1]     at ModdedDex.forFormat (C:\Users\Zuech\Documents\GitHub\TeamBuilder-Project\node_modules\@pkmn\sim\build\sim\dex.js:129:39)`
`[1]     at new TeamValidator (C:\Users\Zuech\Documents\GitHub\TeamBuilder-Project\node_modules\@pkmn\sim\build\sim\team-validator.js:141:30)`

The code used server-side for validation is just this:

> const pkg1 = require('@pkmn/sets');
> const pkg2 = require('@pkmn/sim');
> 
> const {Team} = pkg1;
> const {TeamValidator} = pkg2;
> 
> function teamValidate(teamStr, format) {
>     const validator = new TeamValidator(format);
>     return validator.validateTeam(Team.import(teamStr).team);
> }
> 
> module.exports = {
>     teamValidate: teamValidate,
> }

I've tested the code with different teams for `gen7vgc2018` and `gen7vgc2019@@@-Blue Orb,-Red Orb,Z-Move Clause,-Mega,-Dragon Ascent` and it seems to work fine in these formats.

I'll also try to simulate vgc17's ruleset and banlist using custum rules, I'll let you know if the same problem comes out again.

**Comment by scheibo** [comment]
`gen7vgc2017` is implemented as a mod in Pokémon Showdown upstream and mods (like LGPE) are not supported by this repository currently (there are plans to support them, but not in the way Pokémon Showdown handles mods). `gen7vgc2017` is a mod because it depends on SM and not USUM data, and there's no way with custom rules alone to change the `data/`. As such, `gen7vgc2017` (and other formats which depend on modded data) are not currently supported in `@pkmn/sim`.

**Comment by scheibo** [comment]
I think mod support will look something like this:

- create a new `@pkmn/mods` supplementary package for `@pkmn/sim` which contains data for 'canonical' mods like `stadium`/`stadium2`/`letsgo`/`vgc2017` as well as support for OMs (but no data files)
- the `data/` directory will mirror PS / `@pkmn/sim`'s structure (basically PS structure + `index.ts` files)
- the package will provide a `ModdedDex` wrapper class that is parameterized (`ModdedDex<A extends Abilities = Abilities, ..., S extends Species = Species>`) and will delegate to a `@pkmn/dex-type` `Dex` internally (note: `@pkmn/dex` names its class `ModdedDex` -> this should probably be renamed to `DexImpl` or similar)
- `ModdedDex` casts the return value of each of its getters to the appropriate type parameter (ie. `getSpecies()` is cast to `S`) - this is *not* typesafe as it requires as `as any` to work - this is deemed acceptable (don't care about internal typesafety of mods, only care about presenting correct types to the users of the `ModdedDex`)
- `ModdedDex`'s constructor takes a `modid` and partial of mod data that can be applied to the regular `Dex` (basically this is just `Dex.load` but copied and slightly modified). Thus to create a ModdedDex you would do something like:

```ts
const {Dex} = import('@pkmn/sim').Dex;
const letsgoModData = await import('@pkmn/mods/data/letsgo');
const moddedDex = new ModdedDex(Dex, 'letsgo', letsgoModData);
// moddedDex = same as Dex, but supports dex.mod('letsgo') instead of just 'gen<N>'
```
- `@pkmn/dex` and `@pkmn/sim` should both be possible to mod via `ModdedDex` (though only `@pkmn/sim` will also mod `Scripts`)

Then everything that current takes a `Dex` can just be given a `ModdedDex`. This seems reasonable for a v0.2 or v0.3 release of `@pkmn/sim`.

This handles 'mods', but does not solve the problem of team validation for `gen7vgc2017` because the `TeamValidator` relies on the global `Dex` (because PS loves its globals...). **To get things to work, there also needs to be an upstream change for https://github.com/smogon/pokemon-showdown which makes it so `TeamValidator` takes a `Dex` param in its constructor/methods and never refers to the global `Dex` object** (this is in theory pretty trivial to do - just add an optional `dex = Dex` param to the constructor and plumb things through correctly).

**Comment by HeliosVelite** [comment]
> `gen7vgc2017` is implemented as a mod in Pokémon Showdown upstream and mods (like LGPE) are not supported by this repository currently (there are plans to support them, but not in the way Pokémon Showdown handles mods). `gen7vgc2017` is a mod because it depends on SM and not USUM data, and there's no way with custom rules alone to change the `data/`. As such, `gen7vgc2017` (and other formats which depend on modded data) are not currently supported in `@pkmn/sim`.

Oh, it makes sense, thanks for the clarification.
I'll try to build a workaround for this specific format in my code.

Sometimes showdown's code seems like an overkill to me, probably i'm still too unexperienced for it.
Anyway i'd really like to see support for mods (in particular for OMs, it sounds quite interesting), but to be honest i don't think it's an high priority task, as all the most important formats already work as expected to do.

**Comment by scheibo** [comment]
Pushed https://github.com/smogon/pokemon-showdown/commit/8744adaeca0f597de45ea1cfbb5207978a2fb928 upstream and did a bunch of work to add support for mods - `gen7vgc2017` is now working.

```ts
import {Team} from '@pkmn/sets';
import {Dex, ID, ModData, TeamValidator, PokemonSet} from '@pkmn/sim';

(async () => {
const dex = Dex.mod('vgc17' as ID, await import('@pkmn/mods/vgc17') as ModData);

const validator = new TeamValidator('gen7vgc2017', dex);
console.log(validator.validateTeam(Team.import(`
Alakazam-Mega @ Alakazite
Ability: Magic Guard
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
IVs: 0 Atk
- Psychic
- Focus Blast
- Shadow Ball
- Recover

Tangrowth @ Assault Vest
Ability: Regenerator
EVs: 248 HP / 8 Def / 252 SpD
Sassy Nature
IVs: 30 Atk / 30 Def
- Giga Drain
- Knock Off
- Hidden Power [Ice]
- Earthquake

Gliscor @ Toxic Orb
Ability: Poison Heal
EVs: 244 HP / 152 SpD / 112 Spe
Jolly Nature
- Stealth Rock
- Earthquake
- Toxic
- Roost

Magnezone @ Choice Specs
Ability: Magnet Pull
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
IVs: 0 Atk
- Thunderbolt
- Flash Cannon
- Hidden Power [Fire]
- Volt Switch

Tornadus-Therian @ Rocky Helmet
Ability: Regenerator
EVs: 248 HP / 8 Def / 252 Spe
Timid Nature
- Hurricane
- Heat Wave
- Knock Off
- Defog

Magearna @ Fairium Z
Ability: Soul-Heart
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
IVs: 0 Atk
- Shift Gear
- Calm Mind
- Fleur Cannon
- Focus Blast

`)!.team as PokemonSet[]));
})();
```
![Screen Shot 2020-08-30 at 12 16 42](https://user-images.githubusercontent.com/117249/91667613-dc5b2980-eaba-11ea-81ea-488a35893698.png)

This will be released in ~2-3 days (better way wait until the monthly tier shifts land to avoid having to cut packages all the time) as v0.2.0.
