### ISSUE TITLE
Protocol: Support `|deinit` message

### ISSUE THREAD

**Issue by taylorhansen** [pkmn/ps#8]
This message type isn't in the [PROTOCOL](https://github.com/smogon/pokemon-showdown/blob/master/PROTOCOL.md) docs, but is handled by the client when leaving a room. The fix seems simple enough so I could open up a quick PR if needed.

Could there be other unsupported message types? Another one I found is `|noinit` for rejecting room joins, though I'm not sure how far this project wants to go into the undocumented parts of the protocol by reverse-engineering it.

**Comment by scheibo** [comment]
I'd welcome any PRs in this space. I'm only confident I've reverse engineered the undocumented messages relevant for simulation, but messages relevant to creating a client are also desirable (consider also just opening a pull request against the upstream PS repo so that everyone benefits for any messages you have found that have slipped through the cracks)

**Comment by scheibo** [comment]
OK, from `git grep send.*\|` I find the following:

- `|deinit|` - seems to indicate a room should be closed
- `|selectorhtml|{selector}|${content}` - where `selector` is some string, don't know if its range is limited, and `content` is an arbitrary string
- `|refresh|` - tells the client to refresh the page
- `|tempnotify|${key}|${message}` ?
- `|tempnotifyoff|` - seems like the second arg is always `pendingapprovals` in the case of the `show` command, but can also be a room id when used to notify a rank?
- `|noinit|` - blocks joining a room. seems like it can optionally take the form `|noinit|${type}|${message}`?
- `|hidelines|${type}|${userid}|${linecount}` where `link` can either be `unlink`, `delete` or `hide` and `linecount` is optional?
- `|expire|${message}` - sent when a room has been deleted (really i feel PS shouldn't need a `deinit`, `noinit` AND `expire` message, but what do I know?)
- `|modaction|${msg}` / - `|c~|` - can't tell if actual protocol or just hacky internal crap?
- `|askreg|${userid}` - asks the winner of a rated battle to register


There's also all the `MiscArgs` which weren't documented either: <https://github.com/pkmn/ps/blob/4ff6f1e8d522c9704c8156551310b812b66eaf7a/protocol/src/index.ts#L643-L654>

Let's see if we can't find someone to document this mess upstream...

**Comment by taylorhansen** [comment]
Maybe for now I could just add them to MiscArgs and `Protocol.parse`. Would anything have to change in the import scripts?

**Comment by scheibo** [comment]
No. To add support for the args you need to add them to MiscArgs (and make sure theyre corrected typed), to the map tracking all the protocol keys in the same file, and then add support to the verifier to validate the messages type at run time. If you want to take a stab at this that would be great, otherwise I will probably crank something out tomorrow before the release

**Comment by taylorhansen** [comment]
Sure, I'll see what I can do.

**Comment by scheibo** [comment]
You might have trouble with the tests - you need to `subpkg link` to make sure the packages interconnect to each other (this is coincidentally why GH reports the repo as failing currently, its not set up to do the `subpkg link` step and instead is dependent on new packages being released. This is somewhat intentional - it's valuable to have a way to verify the **released** packages work with each other, but when developing locally you want them all to be linked together). Furthermore, to run the tests just from the `protocol` package you'll want to run `subpkg test protocol` from the root. I think https://github.com/pkmn/ps/blob/master/CONTRIBUTING.md covers more of this.
